### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by edbond** [ruby-formatter/sublime-rufo#2]
Stoped working after update to 1.0
Tried to remove package and repository and install again.

Any way I can debug the plugin, see debug output?

Rufo is installed using 'rvm all gem install rufo'
mac, Sublime dev 3129

rufo command works fine.

**Comment by mjago** [comment]
Fixed with #3

**Comment by edbond** [comment]
Works after "Package Update", thanks!
